# Generated by Django 5.2 on 2025-05-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_alter_order_user_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='grocery_app.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'Seller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery_app.user'),
        ),
    ]
